plugins:
  - name: "evacuate"
    restrictions:
      - name: "actionstatus"
      - name: "timeinterval"
        config:
          interval: "50"
  - name: "*"
    restrictions:
      - name: "actionstatus"
      - name: "timeinterval"
        config:
          interval: "60"


